version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/locale/bundle/gems
    env_file: .env
    environment: 
      RAILS_ENV: development
  
  mongo-service:
    image: "mongo:4.4.0"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
    environment:
      - MONGO_INITDB_DATABASE=trustvox_complaints_api_development
      - MONGO_INITDB_DATABASE=trustvox_complaints_api_test

volumes:
  gem_cache:
  mongodb: